package cn.com.domain;
// Generated 2017-9-19 16:11:32 by Hibernate Tools 3.4.0.CR1

/**
 * Booktype generated by hbm2java
 */
public class Booktype implements java.io.Serializable {

	private Integer id;
	private String typeName;
	private String remarks;
	private Integer parentid;
	private Integer state;
	private String isDelete;

	public Booktype() {
	}

	public Booktype(Integer id) {
		this.id = id;
	}

	public Booktype(Integer id, String typeName, String remarks, Integer parentid, Integer state, String isDelete) {
		this.id = id;
		this.typeName = typeName;
		this.remarks = remarks;
		this.parentid = parentid;
		this.state = state;
		this.isDelete = isDelete;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

}
