package cn.com.domain;
// Generated 2017-9-19 16:11:32 by Hibernate Tools 3.4.0.CR1

import java.util.Comparator;

/**
 * Columnlist generated by hbm2java
 */
public class Columnlist implements java.io.Serializable{

	private Integer id;
	private String name;
	private Integer level;
	private Integer parent;
	private Boolean isDelete;
	private Boolean hasContent;

	public Columnlist(String name, Integer level, Integer parent, Boolean hasContent) {
		this.name = name;
		this.level = level;
		this.parent = parent;
		this.hasContent = hasContent;
	}

	public Columnlist() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getParent() {
		return parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public Boolean getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	public Boolean getHasContent() {
		return hasContent;
	}

	public void setHasContent(Boolean hasContent) {
		this.hasContent = hasContent;
	}

}
