package cn.com.domain;
// Generated 2017-11-8 10:58:45 by Hibernate Tools 3.4.0.CR1

/**
 * Keywords generated by hbm2java
 */
public class Keywords implements java.io.Serializable {

	private int id;
	private String name;

	public Keywords(String name) {
		this.name = name;
	}

	public Keywords() {
	}

	public Keywords(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
