package cn.com.domain;
// Generated 2017-10-13 16:11:53 by Hibernate Tools 3.4.0.CR1

/**
 * Links generated by hbm2java
 */
public class Links implements java.io.Serializable {

	private Integer id;
	private String title;
	private String url;
	private String imgsrc;
	private String isDelete;

	public Links() {
	}

	public Links(String title, String url, String imgsrc, String isDelete) {
		this.title = title;
		this.url = url;
		this.imgsrc = imgsrc;
		this.isDelete = isDelete;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getImgsrc() {
		return this.imgsrc;
	}

	public void setImgsrc(String imgsrc) {
		this.imgsrc = imgsrc;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

}
