package cn.com.domain;
// Generated 2017-9-19 16:11:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private String id;
	private String operator;
	private String operationContent;
	private Date operationDate;
	public Log() {
	}

	public Log(String id) {
		this.id = id;
	}

	public Log(String id, String operator, String operationContent, Date operationDate) {
		this.id = id;
		this.operator = operator;
		this.operationContent = operationContent;
		this.operationDate = operationDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getOperationContent() {
		return this.operationContent;
	}

	public void setOperationContent(String operationContent) {
		this.operationContent = operationContent;
	}

	public Date getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}

}
