package cn.com.domain;
// Generated 2017-9-19 16:11:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

    private int id;
    private String title;
    private String userName;
    private String message;
    private Date createTime;
    private String toPerson;
    private Integer userId;
    private String type;
    private String isDelete;
    private Integer replyId;
    private Boolean show;
    private String tel;

    public Message() {
    }

    public Message(int id, String title, String userName, String message, Date createTime, String toPerson, Integer userId, String type, String isDelete, Integer replyId, Boolean show) {
        this.id = id;
        this.title = title;
        this.userName = userName;
        this.message = message;
        this.createTime = createTime;
        this.toPerson = toPerson;
        this.userId = userId;
        this.type = type;
        this.isDelete = isDelete;
        this.replyId = replyId;
        this.show = show;
    }

    public Message(int id, String title, String userName, String message, Date createTime, String toPerson, Integer userId, String type, String isDelete, Integer replyId, Boolean show, String tel) {
        this.id = id;
        this.title = title;
        this.userName = userName;
        this.message = message;
        this.createTime = createTime;
        this.toPerson = toPerson;
        this.userId = userId;
        this.type = type;
        this.isDelete = isDelete;
        this.replyId = replyId;
        this.show = show;
        this.tel = tel;
    }

    public Message(int id) {
        this.id = id;
    }


    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getToPerson() {
        return this.toPerson;
    }

    public void setToPerson(String toPerson) {
        this.toPerson = toPerson;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    public Integer getReplyId() {
        return replyId;
    }

    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    public Boolean getShow() {
        return show;
    }

    public void setShow(Boolean show) {
        this.show = show;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }
}
