package cn.com.domain;
// Generated 2017-11-8 11:12:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * NewsKeywords generated by hbm2java
 */
public class NewsKeywords implements java.io.Serializable {

	private Integer id;
	private String news;
	private Integer keywords;
	private Date createTime;

	public NewsKeywords() {
	}

	public NewsKeywords(String news, Integer keywords) {
		this.news = news;
		this.keywords = keywords;
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNews() {
		return this.news;
	}

	public void setNews(String news) {
		this.news = news;
	}

	public Integer getKeywords() {
		return this.keywords;
	}

	public void setKeywords(Integer keywords) {
		this.keywords = keywords;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
