package cn.com.domain;
// Generated 2017-9-19 16:11:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Orderlist generated by hbm2java
 */
public class Orderlist implements java.io.Serializable {

	private int id;
	private String orderNo;
	private String productName;
	private Date buy;
	private byte[] buyMan;
	private Byte productPrice;
	private byte[] isDelete;

	public Orderlist() {
	}

	public Orderlist(int id) {
		this.id = id;
	}

	public Orderlist(int id, String orderNo, String productName, Date buy, byte[] buyMan, Byte productPrice,
			byte[] isDelete) {
		this.id = id;
		this.orderNo = orderNo;
		this.productName = productName;
		this.buy = buy;
		this.buyMan = buyMan;
		this.productPrice = productPrice;
		this.isDelete = isDelete;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Date getBuy() {
		return this.buy;
	}

	public void setBuy(Date buy) {
		this.buy = buy;
	}

	public byte[] getBuyMan() {
		return this.buyMan;
	}

	public void setBuyMan(byte[] buyMan) {
		this.buyMan = buyMan;
	}

	public Byte getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(Byte productPrice) {
		this.productPrice = productPrice;
	}

	public byte[] getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(byte[] isDelete) {
		this.isDelete = isDelete;
	}

}
