package cn.com.domain;
// Generated 2017-11-7 17:13:49 by Hibernate Tools 3.4.0.CR1

/**
 * Recommend generated by hbm2java
 */
public class Recommend implements java.io.Serializable {

	private Integer id;
	private Integer hotBook;
	private String comment;
	private String authorName;

	public Recommend() {
	}

	public Recommend(Integer hotBook, String comment) {
		this.hotBook = hotBook;
		this.comment = comment;
	}

	public Recommend(Integer id, Integer hotBook, String comment) {
		this.id = id;
		this.hotBook = hotBook;
		this.comment = comment;
	}

	public Recommend(Integer id, Integer hotBook, String comment, String authorName) {
		this.id = id;
		this.hotBook = hotBook;
		this.comment = comment;
		this.authorName = authorName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getHotBook() {
		return this.hotBook;
	}

	public void setHotBook(Integer hotBook) {
		this.hotBook = hotBook;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getAuthorName() {
		return authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}
}
