package cn.com.domain;
// Generated 2017-12-25 13:34:10 by Hibernate Tools 3.4.0.CR1

/**
 * Resource generated by hbm2java
 */
public class Resource implements java.io.Serializable {

	private Integer id;
	private String resourceName;
	private String resourceUrl;
	private String resourceType;
	private String release;

	public Resource() {
	}

	public Resource(String resourceName) {
		this.resourceName = resourceName;
	}

	public Resource(String resourceName, String resourceUrl, String resourceType, String release) {
		this.resourceName = resourceName;
		this.resourceUrl = resourceUrl;
		this.resourceType = resourceType;
		this.release = release;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public void setRelease(String release){
		this.release = release;
	}

	public String getRelease(){
		return this.release;
	}

}
