package cn.com.domain;
// Generated 2017-11-27 14:53:54 by Hibernate Tools 3.4.0.CR1

/**
 * ShippingAddress generated by hbm2java
 */
public class ShippingAddress implements java.io.Serializable {

	private Integer id;
	private int userid;
	private String province;
	private String city;
	private String area;
	private String addressDetail;
	private String code;
	private String consignee;
	private String phone;
	private String tel;

	public ShippingAddress() {
	}

	public ShippingAddress(int userid) {
		this.userid = userid;
	}

	public ShippingAddress(int userid, String province, String city, String area, String addressDetail, String code,
			String consignee, String phone, String tel) {
		this.userid = userid;
		this.province = province;
		this.city = city;
		this.area = area;
		this.addressDetail = addressDetail;
		this.code = code;
		this.consignee = consignee;
		this.phone = phone;
		this.tel = tel;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getAddressDetail() {
		return this.addressDetail;
	}

	public void setAddressDetail(String addressDetail) {
		this.addressDetail = addressDetail;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getConsignee() {
		return this.consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

}
